; PlatformIO Project Configuration File
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor options
monitor_speed = 115200

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=3

; Library dependencies
lib_deps = 
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
    blynk/Blynk

; Source directories
src_dir = main

; For building test files, you can create separate environments
[env:test_inmp441]
platform = espressif32
board = esp32dev
framework = arduino
src_dir = tests/03_inmp441
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
